### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by CircArgs** [CircArgs/headjack-pre#7]
- [ ] Creating DJ nodes from existing sources using semantic instructions
- [ ] Summarizing existing nodes using node descriptions and a knowledge base
- [ ] Finding best metrics and dimensions to answer a semantic question
- [ ] Given a source node, get all the descriptions of downstream nodes and use them to answer "How is this node being used?"
- [ ] Find related metrics or dimensions given a snippet of text from a document (might be the same feature as 3)
